// ===== Datos compartidos por index.html y experiencias.html =====

const experiencias = [
    {
        nombre: "Playa Las Palmas",
        categoria: "Playas",
        precio: 50,
        horario: "08:00 - 18:00",
        duracion: 4,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.9847, lng: -79.6570 },
        recomendaciones: "Usar protector solar",
        imagen: "https://i.ytimg.com/vi/crYihKtMbGs/sddefault.jpg",
        descripcion: "Playa urbana ideal para turismo familiar.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Playa de Tonsupa",
        categoria: "Playas",
        precio: 30,
        horario: "08:00 - 18:00",
        duracion: 5,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.9120, lng: -79.8070 },
        recomendaciones: "Disfrutar del atardecer",
        imagen: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
        descripcion: "Playa urbana ideal para turismo familiar.",
        ubicacion: "Tonsupa"
    },
    {
        nombre: "Atacames",
        categoria: "Playas",
        precio: 20,
        horario: "09:00 - 20:00",
        duracion: 6,
        franja: "todo el día",
        coordenadas: { lat: 0.8700, lng: -79.8420 },
        recomendaciones: "Probar la comida típica a la orilla del mar",
        imagen: "https://i.ytimg.com/vi/AJEPcXjO64U/maxresdefault.jpg",
        descripcion: "Uno de los destinos más visitados del Ecuador.",
        ubicacion: "Atacames"
    },
    {
        nombre: "Festival Marimba",
        categoria: "Cultura",
        precio: 10,
        horario: "18:00 - 22:00",
        duracion: 3,
        franja: "noche",
        coordenadas: { lat: 0.9680, lng: -79.6520 },
        recomendaciones: "Asistir con ropa cómoda para bailar",
        imagen: "https://ec.viajandox.com/uploads/Festival%20Internacional%20de%20M%C3%BAsica%20y%20Danza_4.jpg",
        descripcion: "Música tradicional afroesmeraldeña.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Ruta Gastronómica",
        categoria: "Gastronomía",
        precio: 25,
        horario: "12:00 - 16:00",
        duracion: 3,
        franja: "tarde",
        coordenadas: { lat: 0.9800, lng: -79.6560 },
        recomendaciones: "Probar el encocado de camarón",
        imagen: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=900&q=80",
        descripcion: "Recorrido por la gastronomía local.",
        ubicacion: "Centro"
    },
    {
        nombre: "Reserva Mache Chindul",
        categoria: "Naturaleza",
        precio: 40,
        horario: "07:00 - 16:00",
        duracion: 8,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.4900, lng: -79.8600 },
        recomendaciones: "Llevar zapatos adecuados para montaña",
        imagen: "https://pbs.twimg.com/media/FZu7eRrXEAMRECx.jpg",
        descripcion: "Bosque tropical y biodiversidad.",
        ubicacion: "Muisne"
    },
    {
        nombre: "Tour Histórico",
        categoria: "Recorridos",
        precio: 15,
        horario: "09:00 - 12:00",
        duracion: 2,
        franja: "mañana",
        coordenadas: { lat: 0.9660, lng: -79.6540 },
        recomendaciones: "Tomar nota de los datos históricos",
        imagen: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0a/48/ed/d0.jpg",
        descripcion: "Historia y patrimonio.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Mompiche",
        categoria: "Playas",
        precio: 18,
        horario: "08:00 - 18:00",
        duracion: 6,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.5100, lng: -80.0260 },
        recomendaciones: "Llevar tabla de surf si lo practicas",
        imagen: "https://velturtravel.com/wp-content/uploads/DECAMERON-MOMPICHE2-1.jpg",
        descripcion: "Surf y naturaleza.",
        ubicacion: "Mompiche"
    },
    {
        nombre: "Parque Familiar",
        categoria: "Familia",
        precio: 8,
        horario: "09:00 - 17:00",
        duracion: 2,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.9600, lng: -79.6600 },
        recomendaciones: "Ideal para ir con niños",
        imagen: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80",
        descripcion: "Actividades para toda la familia.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Festival Cultural",
        categoria: "Eventos",
        precio: 5,
        horario: "17:00 - 22:00",
        duracion: 4,
        franja: "noche",
        coordenadas: { lat: 0.9670, lng: -79.6500 },
        recomendaciones: "Llegar temprano para conseguir buen puesto",
        imagen: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80",
        descripcion: "Presentaciones artísticas.",
        ubicacion: "Malecón"
    },
    {
        nombre: "Escuela de Marimba",
        categoria: "Música y Danza",
        precio: 12,
        horario: "15:00 - 17:00",
        duracion: 2,
        franja: "tarde",
        coordenadas: { lat: 0.9690, lng: -79.6530 },
        recomendaciones: "Participar en las dinámicas de clase",
        imagen: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80",
        descripcion: "Aprendizaje musical.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Same",
        categoria: "Playas",
        precio: 22,
        horario: "08:00 - 18:00",
        duracion: 5,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.8300, lng: -79.9500 },
        recomendaciones: "Disfrutar del ambiente exclusivo",
        imagen: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?auto=format&fit=crop&w=900&q=80",
        descripcion: "Destino turístico premium.",
        ubicacion: "Same"
    },
    {
        nombre: "Feria Gastronómica",
        categoria: "Eventos",
        precio: 10,
        horario: "10:00 - 15:00",
        duracion: 3,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.9700, lng: -79.6540 },
        recomendaciones: "Probar los dulces tradicionales",
        imagen: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80",
        descripcion: "Comida típica esmeraldeña.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Ruta del Spondylus (tramo Esmeraldas)",
        categoria: "Recorridos",
        precio: 30,
        horario: "08:00 - 17:00",
        duracion: 8,
        franja: "todo el día",
        coordenadas: { lat: 0.8700, lng: -79.8400 },
        recomendaciones: "Ideal en vehículo propio, con paradas libres",
        imagen: null,
        descripcion: "Recorrido costero por la vía E15 entre las playas emblemáticas de la provincia.",
        ubicacion: "Costa de Esmeraldas"
    },
    {
        nombre: "Avistamiento de Ballenas Jorobadas",
        categoria: "Recorridos",
        precio: 40,
        horario: "09:00 - 12:00",
        duracion: 3,
        franja: "mañana",
        coordenadas: { lat: 0.8600, lng: -79.8740 },
        recomendaciones: "Temporada: junio a septiembre",
        imagen: null,
        descripcion: "Salida en lancha desde Súa para observar ballenas jorobadas.",
        ubicacion: "Súa"
    },
    {
        nombre: "Manglares de Valdez (Limones)",
        categoria: "Recorridos",
        precio: 25,
        horario: "08:00 - 12:00",
        duracion: 4,
        franja: "mañana",
        coordenadas: { lat: 1.0600, lng: -78.9900 },
        recomendaciones: "Llevar repelente y gorra",
        imagen: null,
        descripcion: "Recorrido fluvial entre manglares en el norte de la provincia.",
        ubicacion: "Valdez, Eloy Alfaro"
    },
    {
        nombre: "Ruta Cultural Chachi",
        categoria: "Recorridos",
        precio: 35,
        horario: "08:00 - 14:00",
        duracion: 6,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.4300, lng: -79.2100 },
        recomendaciones: "Respetar las costumbres de la comunidad",
        imagen: null,
        descripcion: "Inmersión cultural con la nacionalidad Chachi en el río Canandé.",
        ubicacion: "Río Canandé, Quinindé"
    },
    {
        nombre: "Playa Escondida",
        categoria: "Naturaleza",
        precio: 15,
        horario: "08:00 - 17:00",
        duracion: 5,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.7800, lng: -80.0300 },
        recomendaciones: "Llevar agua y snacks, zona poco comercial",
        imagen: null,
        descripcion: "Refugio ecológico de playa rústica y tranquila.",
        ubicacion: "Tonchigüe - Punta Galera"
    },
    {
        nombre: "Laguna de Cube",
        categoria: "Naturaleza",
        precio: 12,
        horario: "08:00 - 16:00",
        duracion: 4,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.3900, lng: -79.7000 },
        recomendaciones: "Ideal para observación de aves",
        imagen: null,
        descripcion: "Humedal de importancia internacional en la zona de Quinindé.",
        ubicacion: "Quinindé"
    },
    {
        nombre: "Reserva Manglares Cayapas-Mataje",
        categoria: "Naturaleza",
        precio: 20,
        horario: "07:00 - 15:00",
        duracion: 5,
        franja: "mañana-tarde",
        coordenadas: { lat: 1.2000, lng: -78.9000 },
        recomendaciones: "Hogar de los manglares más altos del mundo",
        imagen: null,
        descripcion: "Reserva ecológica de manglares en San Lorenzo.",
        ubicacion: "San Lorenzo"
    },
    {
        nombre: "Reserva Marina Galera-San Francisco",
        categoria: "Naturaleza",
        precio: 18,
        horario: "08:00 - 16:00",
        duracion: 4,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.8200, lng: -80.0500 },
        recomendaciones: "Apta para snorkel y buceo con guía",
        imagen: null,
        descripcion: "Área marina protegida con arrecifes y vida submarina.",
        ubicacion: "Punta Galera, Muisne"
    },
    {
        nombre: "Encocao de Mariscos",
        categoria: "Gastronomía",
        precio: 8,
        horario: "12:00 - 15:00",
        duracion: 0.5,
        franja: null,
        coordenadas: { lat: 0.9800, lng: -79.6560 },
        recomendaciones: "El plato insignia de la provincia",
        imagen: null,
        descripcion: "Degustación del tradicional encocao con leche de coco.",
        ubicacion: "Malecón de Esmeraldas"
    },
    {
        nombre: "Tapao Arrecho",
        categoria: "Gastronomía",
        precio: 7,
        horario: "12:00 - 15:00",
        duracion: 0.5,
        franja: null,
        coordenadas: { lat: 0.9800, lng: -79.6560 },
        recomendaciones: "Receta ancestral esmeraldeña",
        imagen: null,
        descripcion: "Degustación del contundente plato de pescado y plátano.",
        ubicacion: "Centro de Esmeraldas"
    },
    {
        nombre: "Ceviche de Concha",
        categoria: "Gastronomía",
        precio: 6,
        horario: "10:00 - 14:00",
        duracion: 0.5,
        franja: null,
        coordenadas: { lat: 0.9820, lng: -79.6550 },
        recomendaciones: "Acompañar con chifles y limón",
        imagen: null,
        descripcion: "Degustación del ceviche típico de concha prieta.",
        ubicacion: "Las Palmas"
    },
    {
        nombre: "Cocadas Tradicionales",
        categoria: "Gastronomía",
        precio: 3,
        horario: "09:00 - 18:00",
        duracion: 0.5,
        franja: null,
        coordenadas: { lat: 0.9847, lng: -79.6570 },
        recomendaciones: "Probar la blanca y la negra",
        imagen: null,
        descripcion: "Dulce artesanal de coco, herencia afroesmeraldeña.",
        ubicacion: "Malecón Las Palmas"
    },
    {
        nombre: "Fiestas de Independencia de Esmeraldas",
        categoria: "Eventos",
        precio: 5,
        horario: "18:00 - 23:00",
        duracion: 5,
        franja: "noche",
        coordenadas: { lat: 0.9680, lng: -79.6520 },
        recomendaciones: "Agosto, mes de la independencia",
        imagen: null,
        descripcion: "Desfiles, música y celebración cívica de la provincia.",
        ubicacion: "Esmeraldas"
    },
    {
        nombre: "Aqua Park Atacames",
        categoria: "Familia",
        precio: 15,
        horario: "10:00 - 17:00",
        duracion: 4,
        franja: "mañana-tarde",
        coordenadas: { lat: 0.8750, lng: -79.8300 },
        recomendaciones: "Piscinas y toboganes para los pequeños",
        imagen: null,
        descripcion: "Centro de diversión acuática para toda la familia.",
        ubicacion: "Atacames"
    }
];

const EMOJI_CATEGORIA = {
    "Playas": "🏖️",
    "Cultura": "🎭",
    "Música y Danza": "🎵",
    "Gastronomía": "🍤",
    "Recorridos": "🚶",
    "Naturaleza": "🌿",
    "Eventos": "🎉",
    "Familia": "👨‍👩‍👧‍👦"
};

function formatoTiempo(horas) {
    if (horas < 1) return Math.round(horas * 60) + " min";
    const h = Math.floor(horas);
    const m = Math.round((horas - h) * 60);
    return m > 0 ? `${h} h ${m} min` : `${h} h`;
}

function textoEstancia(exp) {
    return formatoTiempo(exp.duracion) + (exp.franja ? ` (${exp.franja})` : "");
}
